### ISSUE TITLE
I'm translating into Italian

### ISSUE THREAD

**Issue by francematt** [liuderchi/atom-i18n#93]
Please help translate: .

locale code: `it`
[locale code table](http://www.science.co.il/language/Codes.php)

files Required translation:
  - `def/it/about.cson`
  - `def/it/context.cson`
  - `def/it/menu_darwin.cson`
  - `def/it/menu_linux.cson`
  - `def/it/menu_win32.cson`
  - `def/it/settings.cson`
  - `def/it/welcome.cson`

* for more info please checkout [CONTRIBUTING.md](https://github.com/liuderchi/atom-i18n/blob/master/CONTRIBUTING.md)

**Comment by liuderchi** [comment]
@francematt thank you for translating Italian 🎉

**Comment by pymike00** [comment]
Hi there guys! Thanks for the amazing job you've done. 

The translation is good, but I've found some issues that I think are worth notifying.

#################
a)
"Toggle" has been translated as "commuta", so that:

"toggle comments" has become "commuta commenti"
"toggle fullscreen" has become "commuta fullscreen"
"toggle menu bar" ==> "commuta barra dei menu"
(... and so on ...)

I think that translating "toggle" as "commuta" is incorrect.

Even tough in a very specific subset of situations and applications "toggle" could be properly translated as "commuta", I really don't think this translation is one of such situations and applications: in Italian commuta is a very specific word, which is mainly used in the fields of Electrical Engineering and Jurisprudence. 

In Italian, toggle should most of the times be translated as "attiva" or "aziona". 

In this specific case I think "attiva" is the one to choose most of the times where "toggle" is needed... because furthermore, it is incorrect to translate something literally, word by word!

- "toggle full screen", for example, should be translated as "modalità a schermo intero" or "attiva modalità a schermo intero" or simply "schermo intero";
- "commuta barra dei menu" could be translated as "nascondi barra dei menu", which makes sense because when the option is available, the action that is triggered by "toggle menu bar" is actually "hide menu bar". 

The two translations I provided as examples are of course, not literal translations, but reflect the proper use of the Italian language. That's the reason why they are also chosen by most companies to translate their software.

Here are a couple of links to support my claims:

WordReference translation:
ITA-ENG http://www.wordreference.com/iten/commuta
ENG-ITA http://www.wordreference.com/enit/toggle

Two of Italy's most valuable resources regarding language, on the meaning of "commuta", and therefore, "commutare" :
http://dizionari.corriere.it/dizionario_italiano/C/commutare.shtml
http://www.treccani.it/vocabolario/commutare/

I am of course, available to support the translation of the project in the best and most correct way possible. So please let me know what do you think about my claims.

##############
b)
In the Edit Menu, "paste without reformatting" hasn't been translated.

##############
c)
I also have a suggestion regarding the application of point number 3 of the Translation Guide.
The hotkey hints preserved with braces wrapped at the end of the (sub)menu labels are often confusing. 

We can for example, press ALT + E to enter the Edit menu, but then confusion starts to kick in:
-to access the copy function, we must of course press CTRL-C
-to access the cut function, we must of course press CTRL-Z
-and so on. 

Some of the hotkey combinations don't actually work (for example, Preferences (Preferenze in Italian) has (P), but ALT + P opens the packages menu. The proper combo to open the preferences menu is CTRL + comma, as already specified in grey scale color, on the left...

In this specific case [ (P) ] I might have misunderstood the concept of hotkey, so let me know.

Anyhow, I think these ambiguities I just pointed out can be challenging especially for newer users, and perhaps even scare them away. 

I think it would be better to just leave the menu labels as they are in the original, English version.

#############

Please let me know what you think.

Thanks for your attention,

Best Regards

**Comment by liuderchi** [comment]
@pymike00 thanks for your work 👍 

> a) "Toggle" has been translated as "commuta", so that: ...

What do you think @francematt @LorenzoAncora ? ([CODEOWNER of it](https://github.com/liuderchi/atom-i18n/blob/master/.github/CODEOWNERS#L19))
Please help and provide your opinion. 🙏 

---

> b) In the Edit Menu, "paste without reformatting" hasn't been translated.

Contribution is really _Welcome_. Please visit [CONTRIBUTING.md](https://github.com/liuderchi/atom-i18n/blob/master/CONTRIBUTING.md) for more info and ask me anything about it 😄 

---

> c) a suggestion regarding the application of point number 3 of the Translation Guide ...

> ... I think it would be better to just leave the menu labels as they are in the original, English version.

  - IMO hotkey prompt is _needed to be shown_ because it provide Linux/Win32 users info to use [menu shortcuts](https://github.com/atom/atom/issues/4057#issue-47734834).
    - e.g. [<kbd>Alt</kbd> -> <kbd>F</kbd> (&File) -> <kbd>O</kbd> (&Open) to open a file](https://github.com/atom/atom/blob/master/menus/win32.cson#L7).

> ... for example, Preferences (Preferenze in Italian) has (P), but ALT + P opens the packages menu...
  - Similarly if a linux user wants to navigate Preferences using keyboard he or she can do
    * holding <kbd>Alt</kbd> then hit [ <kbd>E</kbd> to `Edit`](https://github.com/atom/atom/blob/master/menus/linux.cson#L32)
    * hit [<kbd>P</kbd> to `Preference`](https://github.com/atom/atom/blob/master/menus/linux.cson#L100)
  - of course <kbd>ctrl</kbd> + <kbd>,</kbd> is still working

You now seeing [`Preferenze (P)` rather than `&Preferenze `](https://github.com/liuderchi/atom-i18n/blob/master/def/it/menu_linux.cson#L130). Actually it's a mistake I made in the past.
I _used to_ recommend that always preserve it in braces in the [translation guide](https://github.com/liuderchi/atom-i18n/blob/master/CONTRIBUTING.md#translation-guide). Currently the guide recommend both ways.

Now after consideration I would support: _if possible, try to use hotkey hint inside a word rather than preserve it in braces_. I will emphasize it in the Guide. __So, feel free to change it and in other locales is welcome__.

---
---

FYI: It's fun that github support _markdown text_ to add special format to plain text like
  - `---` gives you a _horizontal rule_
  - `## Some Topic` gives you larger font for more attention
  - `<kbd>Alt</kbd>` gives you keybord

For more info please visit https://guides.github.com/features/mastering-markdown/

**Comment by pymike00** [comment]
Hey there, thanks for your reply and to have considered my idea.

I was pretty tired yesterday when I wrote the post, after a long day of work I have myself made some mistakes while reporting:

> Some of the hotkey combinations don't actually work 

Incorrect: they all work. My bad -.-" sorry about that.

> In the Edit Menu, "paste without reformatting" hasn't been translated.

It seems like this string is not inside any of the files that have been translated by the guys, so it is **not** something that has been forgotten. I will check the location of the string asap. 

Thanks again everyone!

Best Regards

**Comment by LorenzoAncora** [comment]
Hello @pymike00 @liuderchi and thank you for your support.
@pymike00 your doubts are legitimate, but in the commit message I briefly explained the reason for these particular choices.

> I think that translating "toggle" as "commuta" is incorrect. [...]
>Even tough in a very specific subset of situations and applications "toggle" could be properly translated as "commuta", I really don't think this translation is one of such situations and applications: in Italian commuta is a very specific word, which is mainly used in the fields of Electrical Engineering and Jurisprudence.

This requires a detailed explanation, because there are many reasons for this choice. ENG\ITA dictionaries do not always offer a proper translation, they only give an example of a probable translation: Italian cannot be translated 1:1 with English, because we talk with our gestures, with our tone of voice and many environmental factors determinate the correct meaning of a word. Thats why for computers (and politics) we sometimes use particular sets of words. :-)
- I made this choice intentionally, because _attivare_ can be incorrect and I've seen this verb used many times wrongly in other software that was translated automatically.
I am a native speaker and we use _commuta_ to signify that a GUI control can be enabled if (and only if) it is already disabled and disabled if (and only if) it is already enabled.
- _Commutare_ means "attivare" or "disattivare" in relation to the **current** state of the functionality.
You can think of it as "exchanging a state with another state", but it is a common word from many years and is not property of a specific Italian dialect.
- This terminology is system agnostic and will be understood by all users: when Italians see this verb they know that clicking on it will enable/disable something: they know that going back **in the same place** will allow to deactivate the functionality once it is enabled.
If we use "_Attiva_ something" the user will expect that after clicking on it the menu entry will become "_Disattiva_ something", but won't have any guarantee. If this change does not happen or the functionality does not appear on screen immediately the user may (legitimately) think that Atom has a bug, which of course is not true.

Don't worry: before submitting it I've asked other Italian users of Atom to check for readability and comprehensibility (thats why some phrases are a bit verbose, to allow _everyone_ to understand clearly).
Did I clarify your doubts? :-)

**Comment by pymike00** [comment]
Hey there @LorenzoAncora!

Ok perfect, I had missed the commit message so I didn't know it was intentional :)
Yes, doubts have been clarified!

Thanks for your precious work guys!

Have a good one! :)

**Comment by liuderchi** [comment]
@francematt @LorenzoAncora @pymike00 atom-i18n won't be better without your work. 💯 
I will close this issue if everything is clarified : ]

**Comment by pymike00** [comment]
Sure, it's fine by me! :D

**Comment by LorenzoAncora** [comment]
@liuderchi fine for me too. &#10003; &#10003; &#10003;
